### ISSUE TITLE
Intel detection tools appear to be for unrelated vulnerability

### ISSUE THREAD

**Issue by rmc47** [hannob/meltdownspectre-patches#32]
Unless I'm misreading it, the Intel detection and remediation tools linked in 30974332702bc08a325bf8eadfa864ab3d844c8f are for a different security advisory (the Intel AMT vulnerability).

**Comment by gvarisco** [comment]
Correct, got caught in a mistake due to https://www.us-cert.gov/ncas/alerts/TA18-004A
